### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by zaoqi** [gregtyler/SITS-Lua#1]

**Comment by gregtyler** [comment]
Hello,

I'm afraid I never made much progress with this repo (I'm archiving it to make that clearer). It'll do a bit of basic Lua->SITS conversion but it's not at all comprehensive and will fail on even the slightest edge cases.

Basic functionality is that you put your Lua code into the `input.lua` file, run `node index.js` and it'll drop matching SITS code into stdout.

If you want to fork this repo and make it more functional then please feel very welcome. However, I no longer work with SITS so will not be maintaining or expanding it.

All the best,
Greg
